### ISSUE TITLE
There is already a Minesweeper in Brick

### ISSUE THREAD

**Issue by nadia-polikarpova** [heya30/CSE230_JewelLegend#1]
A public brick implementation of Minesweeper already exists: https://dev.to/dkurilo/minesweeper-clone-in-haskell-for-console-321g

You need to pick a different project, or explain how you will make your sufficiently different

**Comment by Eric-Bokai-Zhang** [comment]
After thoroughly investigating current puzzles implemented in Haskell, we choose to change the topic to the game "Jewel Legend", which has not been implemented with Brick. The game can be referenced with: [https://apps.apple.com/us/app/jewel-legend/id902173725](https://apps.apple.com/us/app/jewel-legend/id902173725). The design might be a little different.
